import Head from 'next/head'
import Shape1 from '../public/shape1.svg'
import fruit from '../public/media/fruit.mp4'

export default function Home() {
  return (
    <div>
      <Head>
        <title>feelpart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-10">
        <div className="xl:w-1/2">
          <div className="leading-none text-6xl">
            <span className="font-semibold">Elevate</span> your customer
            experience with video
          </div>
          <div className="py-6 text-lg font-medium">
            Interact with your audience and{' '}
            <span className="font-bold">build stronger connections</span>.
          </div>
          <button className="button-85 font-semibold mt-6 mr-8" role="button">
            Start creating for free
          </button>
        </div>
        <div className="flex items-center mx-auto">
          <div className="w-1/3"></div>
          <div className="w-1/3 relative">
            <Shape1 className="absolute animate-spin-slow -bottom-6 -left-24 w-[800px] text-yellow-400 -z-10" />
            <video
              className="relative w-96 rounded-xl overflow-hidden"
              loop
              muted
              autoPlay>
              <source src={fruit} type="video/mp4" />
            </video>
          </div>
          <div className="w-1/3 flex flex-col gap-3">
            <div className="text-3xl font-semibold">
              Live interactive videos
            </div>
            <div>Get started by recording or uploading your video. </div>
            <div>
              Use <span className="font-semibold">conditional logic</span>,
              multiple response options, video, audio, text responses, contact
              forms, a calendar booking or a payment. 
            </div>
          </div>
        </div>
      </div>

      <footer className="h-40"></footer>
    </div>
  )
}
